### ISSUE TITLE
[Christmas gift] Girlfriend required

### ISSUE THREAD

**Issue by bananaappletw** [tjjh89017/Life#4]
One of my friends, dabo a.k.a. 達博 murmured about Christmas gift recently.
He wanted a girlfriend for Christmas gift.

As his friend and classmate, I recommend him as a candidate for boyfriend.
Currently, Dabo is pursuing master degree of National Chiao Tung University(交通大學).
He is a cordial, chatty sort of person.
He could chat with you all day.
As the expert of engineers, he is specialized in Linux, ARM, kernel, ...... thousands of computer science techniques.
If you have any problem with your computer, he will fix it immediately.
Sometimes, he is called Boss Of Toolman(工頭).
Although he is good at computers, he is an outdoor enthusiast.
He spends thirty minutes riding a bike once a week.
He could take you anywhere with his bike.
The most important of all, he has a smoking hot body.
You might not get enough sleep with him.

Among these benefits, what do you need to be the girlfriend of dabo?
The following conditions are required.

## Basic

- girl
- 16+ years old
- yandere(病嬌)
- Tsundere(傲嬌)

## Extra

- long black hair(黑長直)
- ponytail hair style(馬尾)

If you are qualified and interested in being girlfriend of debo.
Please comment below, or send a pull request to close this issue.
Thanks.

**Comment by tjjh89017** [comment]
呃⋯⋯

**Comment by xnum** [comment]
how about eriri

**Comment by bananaappletw** [comment]
@xnum 
I think Eriri should be a good candidate for girlfriend.
However, she is a girl in anime not in the same world as us.
Maybe Dabo could give it a try?
CDR? (Cross Dimension Romance)
CC: @tjjh89017

**Comment by tjjh89017** [comment]
Life is shit
