### ISSUE TITLE
Volunteer military

### ISSUE THREAD

**Issue by yojo3000** [tjjh89017/Life#6]
國 x 人才招募中心：

達博您好:
國 x 部正在招募『2017 年度反攻 xx 淪陷重災區網軍』
透過 104? 看到您的資料，對您的資歷很有興趣
希望你有機會抽空到山上進行面談

若您對我們的工作機會有興趣，請盡快與我們聯絡確定面談日期。謝謝您!

面試地點：Mountain Top
聯絡電話：KDAyKTIzMTEtNjExNw==

**Comment by tjjh89017** [comment]
囧
